//LOGIN
POST http://localhost:1250/api/auth/login HTTP/1.1
content-type: application/json

{
    "mail" : "dat@gmail.com",
    "password" : "123456"
}

###
//REGISTER
POST http://localhost:1250/api/auth/register HTTP/1.1
content-Type: application/json

{
    "username" : "hoang dat",
    "password" : "123456",
    "mail" : "test04@gmail.com"
}

###
POST  http://localhost:1250/api/message/get-message HTTP/1.1
content-Type: application/json

{
    "id" : "62eaa07fe5819614f3e3c19d"
}